
[general]
live_config_reload = true
import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[bell]
animation = "EaseOutExpo"
duration = 0

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
# family = "MesloLGS Nerd Font Mono"
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
#family = "CaskaydiaCove Nerd Font"
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
#family = "CaskaydiaCove Nerd Font"
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
#family = "CaskaydiaCove Nerd Font"
family = "JetBrainsMono Nerd Font"
style = "Regular"
